In [39]:
import numpy as np

In [48]:
orientations = np.array([0, np.pi/2, np.pi])
# np.array([[np.cos(angle), -np.sin(angle)], [np.sin(angle), np.cos(angle)]])
cos = np.cos(-orientations)
sin = np.sin(-orientations)
rot_matrices = np.array([[cos, -sin], [sin, cos]])
rot_matrices = np.transpose(rot_matrices, (2, 0, 1))
test_angle = np.array((np.cos(np.pi/6), np.sin(np.pi/6)))
test_angle = np.tile(test_angle, (3, 1))
print(test_angle)
result = rot_matrices @ test_angle[:, :, None]
print(result)
sq = result.squeeze()
print(sq)
angles = np.arctan2(result[:, 1, 0], result[:, 0, 0])
angles2 = np.arctan2(sq[:, 1], sq[:, 0])
print(angles2 / np.pi * 180)
print(angles / np.pi * 180)

[[0.8660254 0.5      ]
 [0.8660254 0.5      ]
 [0.8660254 0.5      ]]
[[[ 0.8660254]
  [ 0.5      ]]

 [[ 0.5      ]
  [-0.8660254]]

 [[-0.8660254]
  [-0.5      ]]]
[[ 0.8660254  0.5      ]
 [ 0.5       -0.8660254]
 [-0.8660254 -0.5      ]]
[  30.  -60. -150.]
[  30.  -60. -150.]


In [47]:
np.arctan2(1,0) / np.pi * 180

90.0